#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 commit 이전에 prettier, lint 규칙을 적용합니다..."

# lint-staged 실행
npx lint-staged
if [ $? -ne 0 ]; then
  echo "❌ lint-staged 실행 중 오류가 발생했습니다."
  exit 1
fi

# 삭제된 파일은 제외하고 존재하는 파일만 스테이징
changed_files=$(git diff --name-only --staged --diff-filter=d)
if [ $? -ne 0 ]; then
  echo "❌ 변경된 파일을 가져오는 중 오류가 발생했습니다."
  exit 1
fi

# 존재하는 파일만 다시 스테이징
for file in $changed_files; do
  if [ -f "$file" ]; then
    git add "$file"
  fi
done

echo "✅ 모든 prettier, lint 규칙이 성공적으로 적용되었습니다."